// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJs9qfomCLUphS-QYnNn8t5DNljzJMwM',
    appId: '1:982837748691:web:d3f37825122e67f3590526',
    messagingSenderId: '982837748691',
    projectId: 'social-b28bd',
    authDomain: 'social-b28bd.firebaseapp.com',
    storageBucket: 'social-b28bd.appspot.com',
    measurementId: 'G-WRS2ZS823T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGG8URnrwBJ5Ev0Fir84qxdxlrJh7-z8',
    appId: '1:982837748691:android:63a63b323c0834cb590526',
    messagingSenderId: '982837748691',
    projectId: 'social-b28bd',
    storageBucket: 'social-b28bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5vIzfMnJ5D_I32M5PLR4s68RUVK0b-Q',
    appId: '1:982837748691:ios:6781a1b106647b2a590526',
    messagingSenderId: '982837748691',
    projectId: 'social-b28bd',
    storageBucket: 'social-b28bd.appspot.com',
    iosClientId: '982837748691-78p6sfpf580cm1b79ud7tj2o23f79nf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5vIzfMnJ5D_I32M5PLR4s68RUVK0b-Q',
    appId: '1:982837748691:ios:684c994d29684784590526',
    messagingSenderId: '982837748691',
    projectId: 'social-b28bd',
    storageBucket: 'social-b28bd.appspot.com',
    iosClientId: '982837748691-mo1vtuk1crtalmss5dap49nn0ofrjchd.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
